version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: SalesApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#2025@
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - evaluation-network

  sales-api:
    image: sales-api
    build:
      context: .
      dockerfile: src/SalesApi/Dockerfile
    container_name: sales-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      - ConnectionStrings__SalesApiDb=Host=db;Database=SalesApi;Username=postgres;Password=postgres#2025@;Port=5432
    networks:
      - evaluation-network

  gateway:
    image: ocelot-gateway
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    container_name: ocelot-gateway
    depends_on:
      sales-api:
        condition: service_started
    ports:
      - "7777:7777"
    environment:
      - ASPNETCORE_URLS=http://+:7777
    networks:
      - evaluation-network

networks:
  evaluation-network:
    driver: bridge
